{% set name = "amply" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb12dcb49d16b168c02be128a1527ecde50211e4bd94af76ff4e67707f5a2d38

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
    - setuptools_scm
  run:
    - python >=3.4
    - docutils >=0.3
    - pyparsing

test:
  imports:
    - amply
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/willu47/amply
  summary: Amply allows you to load and manipulate AMPL/GLPK data as Python data structures
  license: EPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
